ruleset:
  - expression: (?i).*fatal.*
    colorscheme:
      foreground: '#FF00B'
      background: ''
  - expression: (?i).*error.*
    colorscheme:
      foreground: '#FFA500'
      background: ""
  - expression: (?i).*warn.*
    colorscheme:
      foreground: '#FFFF00'
      background: ""
default:
    foreground: '#ADD8E6'
    background: ""
